# Generated by Django 6.0.3 on 2026-08-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_subscriber_alter_post_image_alter_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
